Removing all dependency to Guard.NET.
arcus-azure/arcus.webapi pull request #465
Opened 2024-12-31 15:53 UTC by joachimgoris

As per issue 463. This PR removes all dependency on Guard.NET. All checks done by Guard.NET have been replaced with `if` checks.

2025-01-01 05:47 UTC, stijnmoreels requested changes
Thx a lot for your work on this and your investment in Arcus! Greatly appriciated.
It's a big PR, so I'll write some comments here that are related to tons of files here:
* It's a Micorosft code style to place a blank linke between curly braces and the next (non-curly brace) line. Now, all the if statements are glued togehter, which conflicts the current style in the repo.
* In method overloads, we previously had several 'paranoia' checks which duplicated things. Especially now that we are responsible for the checks, it might be better to opt for a centralized approach and only check the values where there are used. It helps with clarity, too.
* There are a lot of places where argument names are set. I believe in lots of these cases, that is unnecessary.

2025-01-01 05:47 UTC, stijnmoreels commented on src/Arcus.WebApi.Logging.AzureFunctions/Extensions/IFunctionsWorkerApplicationBuilderExtensions.cs
> +            if (builder is null)
With overloads, you could remove the checks if the value it checks isn't used by the method itself. In the previous code, there were some extensive 'paranoia' guards.

2025-01-01 05:47 UTC, stijnmoreels commented on src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationClientOptions.cs
> +            if (telemetryContext == null)
```suggestion
            if (telemetryContext is null)
```
Best to use the same equalization throughout.

2025-01-01 05:47 UTC, stijnmoreels commented on src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationInfoAccessor.cs
> +                throw new ArgumentNullException(paramName: nameof(contextAccessor));
Reason why there's extensive argument names? In lots of cases (like here), it's unnecessary.

2025-01-01 05:47 UTC, stijnmoreels commented on src/Arcus.WebApi.Logging/Extensions/IServiceCollectionExtensions.cs
> +            }
```suggestion
```
Is already checked in overload and not used here.

2025-01-01 05:47 UTC, stijnmoreels commented on src/Arcus.WebApi.Security/Authentication/Certificates/CertificateAuthenticationConfigBuilder.cs
> +            if (configuredKey is null)
Should be checked for blank, not only `null`.
But you can also limit the guard checks to the places where it is actually used and not passed arround.

2025-01-01 05:47 UTC, stijnmoreels commented on src/Arcus.WebApi.Security/Authentication/Certificates/CertificateAuthenticationValidator.cs
> +            {
```suggestion
            }

            if (services is null)
            {
```
It's a bit a Microsoft style that there is a blank space between curly braces and the next line.

2025-01-01 05:47 UTC, stijnmoreels commented on src/Arcus.WebApi.Tests.Integration/Fixture/HttpRequestBuilder.cs
> +            if (path.StartsWith('/'))
👍

2025-01-02 00:23 UTC, joachimgoris commented on src/Arcus.WebApi.Logging.AzureFunctions/Extensions/IFunctionsWorkerApplicationBuilderExtensions.cs
> +            if (builder is null)
I'll reduce the amount of checks and attempt to centralize them.

2025-01-02 00:23 UTC, joachimgoris commented on src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationClientOptions.cs
> +            if (telemetryContext == null)
This was an error on my part, good spot!

2025-01-06 09:35 UTC, joachimgoris commented on src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationClientOptions.cs
> +            if (telemetryContext == null)
The `is not` cannot be used in C# 8.0. So `!=` will still have to be used in at least 2 instances.

2025-01-06 09:37 UTC, stijnmoreels commented on src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationClientOptions.cs
> +            if (telemetryContext == null)
Yes, that's fine, as long as it's used the same everywhere.

2025-01-06 10:53 UTC, joachimgoris commented on src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationInfoAccessor.cs
> +                throw new ArgumentNullException(paramName: nameof(contextAccessor));
I started adding these for clarity between the order of the arguments of `ArgumentException` and `ArgumentNullException`, since for some reason they are switched. But I stopped adding them when I didn't feel they added any clarity. I forgot to remove them in the first files I adapted.

2025-01-07 05:21 UTC, stijnmoreels commented on src/Arcus.WebApi.Logging.AzureFunctions/AzureFunctionsRequestTrackingMiddleware.cs
> +            BindingMetadata bindingMetadata = context.FunctionDefinition.InputBindings.Values.FirstOrDefault(a => a.Type == "httpTrigger") ?? throw new InvalidOperationException(
This chnge is a bit unrelated to the guard.net stuff, nd I believe it is not an improvement readability-wise.

2025-01-07 05:21 UTC, stijnmoreels commented on src/Arcus.WebApi.Logging.Core/Correlation/CorrelationInfoUpstreamServiceOptions.cs
> +                    throw new ArgumentNullException(paramName: nameof(value), "Requires a function to generate the operation parent ID");
```suggestion
                    throw new ArgumentNullException(nameof(value), "Requires a function to generate the operation parent ID");
```

2025-01-07 05:21 UTC, stijnmoreels commented on src/Arcus.WebApi.Logging.Core/Correlation/CorrelationInfoUpstreamServiceOptions.cs
> +                    throw new ArgumentException(message: "Requires a non-blank value for the operation parent ID request header name", paramName: nameof(value));
```suggestion
                    throw new ArgumentException("Requires a non-blank value for the operation parent ID request header name", nameof(value));
```

2025-01-07 05:21 UTC, stijnmoreels commented on src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelation.cs
> +            _httpContextAccessor = httpContextAccessor ?? throw new ArgumentNullException(paramName: nameof(httpContextAccessor), message: "Requires a HTTP context accessor to get the current HTTP co
```suggestion
            _httpContextAccessor = httpContextAccessor ?? throw new ArgumentNullException(nameof(httpContextAccessor), "Requires a HTTP context accessor to get the current HTTP context");
```

2025-01-07 05:21 UTC, stijnmoreels commented on src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelation.cs
> +            _correlationInfoAccessor = correlationInfoAccessor ?? throw new ArgumentNullException(paramName: nameof(correlationInfoAccessor), message: "Requires a correlation info instance to set and
```suggestion
            _correlationInfoAccessor = correlationInfoAccessor ?? throw new ArgumentNullException(nameof(correlationInfoAccessor), "Requires a correlation info instance to set and retrieve the correlation information");
```

2025-01-07 05:21 UTC, stijnmoreels commented on src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelation.cs
> +            _options = options.Value ?? throw new ArgumentNullException(paramName: nameof(options.Value), message: "Requires a value in the set of options to configure the correlation process");
```suggestion
            _options = options.Value ?? throw new ArgumentNullException(nameof(options.Value), "Requires a value in the set of options to configure the correlation process");
```

2025-01-07 05:21 UTC, stijnmoreels commented on src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelation.cs
> +            HttpContext httpContext = _httpContextAccessor.HttpContext ?? throw new ArgumentNullException(paramName: nameof(HttpContext), "Requires a HTTP context from the HTTP context accessor to st
```suggestion
            HttpContext httpContext = _httpContextAccessor.HttpContext ?? throw new ArgumentNullException(nameof(HttpContext), "Requires a HTTP context from the HTTP context accessor to start correlating the HTTP request");
```

2025-01-07 05:21 UTC, stijnmoreels commented on src/Arcus.WebApi.Logging.Core/Extensions/HttpClientExtensions.cs
> +            if (correlationAccessor is null)
Yes, good determination on only guard-check what's being used. 🚀

2025-01-07 05:21 UTC, stijnmoreels commented on src/Arcus.WebApi.Security/Authentication/Certificates/ConfigurationValidationLocation.cs
> +                var configuration = services.GetService<IConfiguration>() ?? throw new KeyNotFoundException(
Unrelated change that does not really make it more readable.

2025-01-07 05:21 UTC, stijnmoreels commented on src/Arcus.WebApi.Security/Authentication/SharedAccessKey/SharedAccessKeyAuthenticationFilter.cs
> +            return foundSecrets is null ? throw new SecretNotFoundException(_secretName) : foundSecrets.ToArray();
Unrelated change that does not make it more readable.
An extra thing to consider when developing for Arcus, is that the code should be super simple and we should avoid unnecessary long lines. In this case, the most important value (the actual found secret) is hidden away at the end of the line, for example; in favor of using a syntactic sugar. Which does not make it more readable.

2025-01-09 08:58 UTC, fgheysels commented on src/Arcus.WebApi.Logging.AzureFunctions/AzureFunctionsRequestTrackingMiddleware.cs
> +            BindingMetadata bindingMetadata = context.FunctionDefinition.InputBindings.Values.FirstOrDefault(a => a.Type == "httpTrigger") ?? throw new InvalidOperationException(
I agree with the readability comment.
If we would expect that the collection always contains at least one item that complies to the filter statement, we could also use `First` instead of `FirstOrDefault` .  Drawback however, is that we we then have to live with the exception that is thrown by `First` if no element is found, which is less clear then the exception we throw ourselves here

2025-01-09 08:59 UTC, fgheysels reviewed
Thanks for this! I think we can complete this PR very soon; there's just some (minor) change request on the readability of a particular change.

2025-01-09 09:32 UTC, joachimgoris commented on src/Arcus.WebApi.Logging.AzureFunctions/AzureFunctionsRequestTrackingMiddleware.cs
> +            BindingMetadata bindingMetadata = context.FunctionDefinition.InputBindings.Values.FirstOrDefault(a => a.Type == "httpTrigger") ?? throw new InvalidOperationException(
I've reverted the change.

2025-01-09 09:55 UTC, joachimgoris commented on src/Arcus.WebApi.Security/Authentication/SharedAccessKey/SharedAccessKeyAuthenticationFilter.cs
> +            return foundSecrets is null ? throw new SecretNotFoundException(_secretName) : foundSecrets.ToArray();
This is indeed something I did not consider before creating this PR.

2025-01-09 13:47 UTC, fgheysels approved these changes

2025-01-10 05:09 UTC, stijnmoreels approved these changes
Thx for this!

2025-01-10 13:31 UTC, joachimgoris commented
@stijnmoreels or @fgheysels I don't have write access to the repository so I'm not allowed to merge my own PR's :smile:

2025-01-10 13:55 UTC, fgheysels commented
> @stijnmoreels or @fgheysels I don't have write access to the repository so I'm not allowed to merge my own PR's 😄

Let me do it for you, thanks again for your contribution and hope to see you again in the (near) future :)

2025-01-11 13:03 UTC, fgheysels commented
It looks like we have some failing unittests.  Can you have a look at it @joachimgoris  ?

2025-01-14 16:01 UTC, joachimgoris commented
@fgheysels unit tests are fixed.

2025-01-15 05:15 UTC, stijnmoreels commented on src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationClientOptions.cs
> +                    throw new ArgumentNullException(nameof(value), "Requires a non-blank value for the HTTP request header where the dependency ID should be added when tracking HTTP dependencies");
```suggestion
                    throw new ArgumentException("Requires a non-blank value for the HTTP request header where the dependency ID should be added when tracking HTTP dependencies", nameof(value));
```

2025-01-15 05:15 UTC, stijnmoreels commented on src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationClientOptions.cs
> +                    throw new ArgumentNullException(nameof(value), "Requires a non-blank value for the HTTP request header where the transaction ID should be added when tracking HTTP dependencies");
```suggestion
                    throw new ArgumentException("Requires a non-blank value for the HTTP request header where the transaction ID should be added when tracking HTTP dependencies", nameof(value));
```

2025-01-15 05:15 UTC, stijnmoreels commented on src/Arcus.WebApi.OpenApi.Extensions/OAuthAuthorizeOperationFilter.cs
> +                throw new ArgumentNullException(nameof(securitySchemaName), "Requires a name for the OAuth2 security scheme");
```suggestion
                throw new ArgumentException("Requires a name for the OAuth2 security scheme", nameof(securitySchemaName));
```

2025-01-15 05:15 UTC, stijnmoreels commented on src/Arcus.WebApi.OpenApi.Extensions/SharedAccessKeyAuthenticationOperationFilter.cs
> +                throw new ArgumentNullException(nameof(securitySchemeName), "Requires a name for the Shared Access Key security scheme");
```suggestion
                throw new ArgumentException("Requires a name for the Shared Access Key security scheme", nameof(securitySchemeName));
```

2025-01-15 05:15 UTC, stijnmoreels commented on src/Arcus.WebApi.OpenApi.Extensions/SharedAccessKeyAuthenticationOperationFilter.cs
> +                throw new ArgumentNullException(nameof(securitySchemeName), "Requires a name for the Shared Access Key security scheme");
```suggestion
                throw new ArgumentException("Requires a name for the Shared Access Key security scheme", nameof(securitySchemeName));
```

2025-01-15 20:40 UTC, fgheysels commented on src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationClientOptions.cs
> +                    throw new ArgumentNullException(nameof(value), "Requires a non-blank value for the HTTP request header where the dependency ID should be added when tracking HTTP dependencies");
That's a difficult one.  `NotNullOrWhitespace` throws an `ArgumentNullException` if the arg is null, otherwise an `ArgumentException`.

2025-01-16 05:24 UTC, stijnmoreels commented on src/Arcus.WebApi.Logging.Core/Correlation/HttpCorrelationClientOptions.cs
> +                    throw new ArgumentNullException(nameof(value), "Requires a non-blank value for the HTTP request header where the dependency ID should be added when tracking HTTP dependencies");
We can start using that once we stop .NET Standard/.NET 6; for now, it's the same functionality as with the guard library.

2025-01-16 12:29 UTC, merged